variables:
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress --errors --fail-at-end -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - build

maven-build:
  tags: [sprebuild]
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS -s ci-settings.xml clean spring-javaformat:apply deploy site-deploy

