variables:
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress --errors --fail-at-end -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - build
  - site

maven-build:
  tags: [sprebuild]
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS -s ci-settings.xml clean spring-javaformat:apply deploy 


site-build:
  tags: [sprebuild]
  stage: site
  dependencies:
    - maven-build
  script:
    - ./mvnw $MAVEN_CLI_OPTS -s ci-settings.xml clean spring-javaformat:apply site-deploy
